name: neeraj_flutter_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: # For internalization.
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0 # library for internalization
  shared_preferences: ^2.0.5 # For storing data in local storage.
  flutter_mobx: ^2.0.0 # for state management and this provides the Observer.
  provider: ^5.0.0 # for state management
  mobx: ^2.0.1 # provides Store
  dio: ^4.0.0 # for APIs calling.
  connectivity: ^3.0.3 # for internet connection check
  shimmer: ^2.0.0 # for shimmer loading
  flutter_blue: ^0.8.0
  permission_handler: ^10.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2 #provides a concrete way of generating files using Dart code, outside of tools
  mobx_codegen: ^2.0.1+3 #for auto generating code for stores.

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/demo.png
    - assets/image/car.png
    - assets/image/SR.png
    - assets/image/excavator.png
    - assets/image/Armytank.95.png
    - assets/image/Homeautomationfinal(2).png
    - assets/image/freerun.png
    - assets/image/radar.png
    - assets/image/obstacleavoiderr.png
    - assets/image/edgedetectorr.png
    - assets/image/Roadroller(2).png
    - assets/image/Dumper-min.png
    - assets/image/Forklift(1).png
    - assets/image/Crane.png
    - assets/image/Catapult.png
    - assets/image/Ballshooterpng.png
    - assets/image/excavator.png
    - assets/image/hammer.png
    - assets/image/soccer.png
    - assets/image/obstacleavoider.png
    - assets/image/edgedetector.png
    - assets/image/linefollower.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          style: normal
        - asset: assets/fonts/Inter-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 600